// Direct download links for the README. They are generated from the version in package.json, so they
// cannot drift from the installers' names: a test fails when the README block differs from this output.
//   node scripts/download-links.js            print the block
//   node scripts/download-links.js --write    rewrite the block in ../README.md
// After raising the version, run it with --write in the same pull request, then publish the release.
const fs = require("node:fs");
const path = require("node:path");

const REPO = "https://github.com/7AZEM7assan/signal-lab";
const START = "<!-- download-links:start (generated by desktop/scripts/download-links.js) -->";
const END = "<!-- download-links:end -->";

function block(version) {
  const url = (file) => `${REPO}/releases/download/v${version}/Signal-Lab-${version}-${file}`;
  return [
    START,
    "| Your computer | Download |",
    "|---|---|",
    `| Mac with Apple silicon (M1 or newer) | [**Download for Mac (Apple silicon)**](${url("mac-arm64.dmg")}) |`,
    `| Mac with an Intel chip | [**Download for Mac (Intel)**](${url("mac-x64.dmg")}) |`,
    `| Windows 10 or 11 | [**Download for Windows**](${url("win-x64.exe")}) · [ARM PCs](${url("win-arm64.exe")}) |`,
    `| Linux (x64) | [**Download AppImage**](${url("linux-x86_64.AppImage")}) · [.tar.gz](${url("linux-x64.tar.gz")}) |`,
    END,
  ].join("\n");
}

function readme() { return path.join(__dirname, "..", "..", "README.md"); }
function version() { return require("../package.json").version; }

// Replace the block between the markers; throws when the markers are missing.
function apply(text, v) {
  const a = text.indexOf("<!-- download-links:start"), b = text.indexOf(END);
  if (a < 0 || b < 0 || b < a) throw new Error("download-links markers not found in README.md");
  return text.slice(0, a) + block(v) + text.slice(b + END.length);
}

module.exports = { block, apply };

if (require.main === module) {
  const v = version();
  if (process.argv.includes("--write")) {
    const file = readme();
    fs.writeFileSync(file, apply(fs.readFileSync(file, "utf8"), v));
    console.log(`README.md download links set to v${v}`);
  } else {
    console.log(block(v));
  }
}
